import {Canciones} from "./Canciones";

const nombres = [
    "Kill This Love",
    "WHISTLE",
    "Pirate",
    "Bad Boy",
    "BOOMBAYAH",
    "Kiss and Make Up",
    "Dream Glow",
    "Go Go",
    "Euphoria",
    "Trivia: Just Dance",
    "Serendipity",
    "DNA",
    "Gashina",
    "Don't Recall",
    "FAKE LOVE",
    "TWIT",
    "Peek-A-Boo",
    "HOME",
    "Tempo",
    "Forever Young",
    "Bon Bon Chocolate",
    "PLAYING WITH FIRE",
    "Adios",
    "Uh-Oh",
    "DALLA DALLA",
    "As If It's Your Last",
    "ME",
    "Control",
    "ICY",
    "Salute",
    "Roller Coaster",
    "Snapping",
    "Buttelflies",
    "Gotta Go",
    "LALALAY",
    "100 Ways",
    "Chica",
    "Dangerous Woman",
    "On My Way",
    "Nothing On You",
    "BANG BANG BANG",
    "Back to Beutiful",
    "Smoke and Fire",
    "HIP",
    "gogobebe",
    "Get It",
    "DUN DUN",
    "RED MOON",
    "Can't You See Me?",
    "Daechwita",
    "PUMA",
    "Maria",
    "NUNU NANA",
    "Not Shy",
    "SHOOT!",
    "Not For Sale",
    "Magic",
    "Anti-Romantic",
    "Dynamite",
    "Butter",   
    "Permission to Dance",
    "Life Goes On",
    "Stay",
    "Boy With Luv",
    "Black Swan",
    "ON",
    "Mixed Up",
    "Cry for Me",
    "Drunk-Dazed",
    "FEVER",
    "Given-Taken",
    "Future Perfect (Pass the MIC)",
    "Blessed-Cursed",
    "Criminal Love",
    "Sweet Venom",
    "Bite Me",
    "Fever",
    "Chaconne",
    "Still Monster",
    "Blind",
    "Fatal Trouble",
    "Moonstruck",
    "XO (Only If You Say Yes)",
    "Orange Flower (You Complete Me)",
    "Lucifer",
    "Attention, please!",
    "Shout Out",
    "Polaroid Love",
    "Go Big or Go Home",
    "ParadoXXX Invasion",
    "TFW (That Feeling When)",
    "Not For Sale",
    "Upper Side Dreamin'",
    "Chasing That Feeling",
    "Loser=Lover",
    "0X1=LOVESONG (I Know I Love You)",
    "Deja Vu",
    "Sugar Rush Ride",
    "Opening Sequence"

]

const cancion: Canciones[] = []; 

for (let i = 0; i <= 100; i++) { 
    // Recorre el array nombres
    // i es el índice de cada elemento del array

    const cancionActual = new Canciones(nombres[i]);
    //Crea una nueva instancia de la clase Canciones con el nombre actual
    // en la posición i del array nombres

    cancion.push(cancionActual);
    //Agrega la cancion al array de canciones
}
